faiss:
  similarity_search_k_docs: 3
  similarity_search_k_feedback: 1

model_params:
  deployment_mode_embedding: local  # local, online
  deployment_mode_llm: openai  # local, online
  hf_model_repo_id: microsoft/Phi-3-mini-4k-instruct
  local_embedding_model: sentence-transformers/all-MiniLM-L6-v2
  local_max_tokens: 1000
  local_model_task_type: text-generation
  local_repetition_penalty: 0.1
  local_top_k: 50
  local_top_p: 0.95
  local_model_id: "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
  online_model_name: deepseek-r1
  openai_api_base: https://genaiapi.cloudsway.net/v1/ai/XNBwkgPQnMudjcbs
  temperature: 0.4

paths:
  document_faiss_path: document_faiss/customer_1/
  ingested_docs_file: ingested_documents.json
  log_file: app.log
  prompt_file: prompt.yaml

prompt:
  system_prompt: >-
    You are FairWorkly's compliance assistant. Provide concise, practical guidance
    using Fair Work Australia context.

text_splitter:
  chunk_overlap: 200
  chunk_size: 1000
